### ISSUE TITLE
Reader mode with dark theme

### ISSUE THREAD

**Issue by idontlikecaesar** [hugolabe/Wike#12]
Reader mode should follow system light/dark theme.

**Comment by idontlikecaesar** [comment]
Exactly! Though it does not follow system theme, Gnome web browser has a dark reader mode. I think you can implement it to your code

**Comment by hugolabe** [comment]
I'm working in a dark mode.
Wikipedia doesn't have one, so I'm doing it using CSS injection. It's not easy because Wikipedia's CSS is very complex and a bit chaotic, so it won't be perfect, but I think a decent result can be obtained.

![wike-dark](https://user-images.githubusercontent.com/18441950/117535423-fb20a100-aff5-11eb-9d25-80bae7b609f2.png)

**Comment by idontlikecaesar** [comment]
Honestly, it looks awesome

**Comment by idontlikecaesar** [comment]
@hugolabe just got the update and dark mode looks neat, thank you very much :) will it follow system theme?

**Comment by hugolabe** [comment]
Thanks @idontlikecaesar. For now it is only possible switch to dark theme through the option in the main menu.
