### ISSUE TITLE
Support custom MediaWiki sites

### ISSUE THREAD

**Issue by bbb651** [hugolabe/Wike#134]
There are a lot of other MediaWiki sites that can make the app a lot more useful, like game wikis (mostly fandom), disto wikis (like the arch wiki), other wikimedia foundations sites (like wiktionary), etc. As far as I know all of these share the same wikimedia api that wikipedia uses. Although it would still require a major rework to the way interacting with the api is currently done.

There are a number of potential issues I can think of:
- How should this interactive with the ui? Should the app be separated into sites or should tabs from different sites be next to each other? Should history and bookmarks be mixed between different sites?  
- Potential technical limitations: Can we reliably detect languages and display them with the current system in other wikis? Do some wikis require javascript for certain functions? Can theming be consistent across wikis?
- The age rating of the app is currently all ages, supporting custom wikis will probably change that since different wikis have different rules, although it's probably not that important since it's like almost any other application with user generated content (e.g. a browser)

**Comment by hugolabe** [comment]
Sorry, but I don't intend to add new services. Technically it poses many problems and would add a very high level of complexity, making the development and maintenance of the app more difficult.

I prefer to keep the app simple and manageable.

**Comment by Shadow15510** [comment]
I'ts quite fun because I've discovered this soft some days ago and I've juste the same idea!

I've actually made a fork, I'm not familiar with CSS but the wikimedia API are all the same so by just modifying the URL in `wikipedia.py` I can access wiktionnary very easily:
![Capture d’écran du 2023-05-10 10-18-57](https://github.com/hugolabe/Wike/assets/67319895/c6d8a98e-9ca7-4f83-8347-4feee36f839b)
I don't try others wikimedia projects but I guess it's the same…

However the dark theme is broken and there is some fixes on the display (e.g. the left column). Maybe we can also select the Wikimedia project in the search bar as the language.

I understand that it makes a lot of additionnal work but I'm ready to work with you. I'll tell you if I get anywhere.
Maybe we can also imagine several Wike projects with one project per Wikimedia project? It's maybe more simple than all in one…

**Comment by Shadow15510** [comment]
For the fun I tried Wikinews and it seems to work pretty well!
![Capture d’écran du 2023-05-11 17-19-31](https://github.com/hugolabe/Wike/assets/67319895/873ac682-0cca-4d2a-a2e2-751939039fa5)

The search suggestion works too.

**Comment by Shadow15510** [comment]
I forgot to give a screenshot of the modified search settings:
![image](https://github.com/hugolabe/Wike/assets/67319895/8782057d-9b56-465c-8517-0fe70b741bbd)

**Comment by upintheairsheep** [comment]
> Sorry, but I don't intend to add new services. Technically it poses many problems and would add a very high level of complexity, making the development and maintenance of the app more difficult.
> 
> I prefer to keep the app simple and manageable.

Can you make custom APIs an advanced setting, not for end users, but for development of this app.
