### ISSUE TITLE
Support for adjusting text/font size

### ISSUE THREAD

**Issue by forteller** [hugolabe/Wike#148]
Hi. Thanks for a great tool!

Just like in regular browsers and many other apps I would appreciate the option to change the size of the text of the articles with Ctrl + +/- and Ctrl + mouse scroll wheel. I find the default size a bit straining to read, and a lot of people have eye sight issues and might need to have a lot larger text.

Thanks!

**Comment by hugolabe** [comment]
You can change the size (as well as the font) of the article text using the option available in the view menu.

![wike-font](https://github.com/hugolabe/Wike/assets/18441950/565954ac-5ac6-46c0-b2c5-dbd414d5c836)

There are no keyboard shortcuts for this, but I don't think it's necessary, since it's something you'll normally only change once to suit your taste.

**Comment by mattiasb** [comment]
The lack of keybindings (I tried with the usual `Ctrl++` and `Ctrl+-`) made me assume there was no support for changing text size. :)
