### ISSUE TITLE
Request for support for saving articles offline

### ISSUE THREAD

**Issue by saligari** [hugolabe/Wike#15]
Great programme!  

One feature that may be a bit complicated to add but I think would make a lot of sense would be to have an offline database of articles as an addition to bookmarking (perhaps an altogether different option to download or perhaps as an option to download a bookmark). 

<3

**Comment by hugolabe** [comment]
Thanks @saligari!

The option to save articles offline is very complicated, because even saving the page's html would still depend on Wikipedia's online infrastructure. I think this is a bit outside the application goals and there are [more specific](https://www.kiwix.org/en/) alternatives to be able to have Wikipedia offline.

An alternative to be able to save articles could be to have the option to export them as pdf, but it is something different ...

**Comment by hugolabe** [comment]
@blocr It's just that Wike doesn't work like that. The content of articles is not fetched through API calls. The API is used to perform the searches and obtain the URL of the article and then a webview is used to display it, in the same way that a browser does.
