### ISSUE TITLE
Filterable or searchable language list

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#40]
It would be nice if the lengthy list of languages in the preferences dialog was filterable or searchable.

**Comment by hugolabe** [comment]
Done 24d1405e192febf63ad98802768fc29a3b9d4a8a
![prefs-languages](https://user-images.githubusercontent.com/18441950/132040345-e77984e6-2cd3-4e94-a7e9-8a33e7c7670f.png)

**Comment by vanillajonathan** [comment]
This is great!

**Comment by vanillajonathan** [comment]
Oh, this was removed in bc88c2ee5b714cc4a02c3b1a5c1ac16426c028e1. 😥️

**Comment by hugolabe** [comment]
Yes, as indicated in the commit, there were unexpected closings of the preferences window.

I don't know why, since the filtering function is quite simple and similar to the one used eg. in the language selection popover, so I preferred to remove it.

It doesn't seem very important to me either, as this list will normally be used only once to choose the languages you want to have available, and it is easy to find any language as they are sorted alphabetically.

**Comment by hugolabe** [comment]
It did not show any errors. The window was simply closed.
Yes, I can try it again in GTK4.
