### ISSUE TITLE
Use GTK's font picker for "Use Custom Font"

### ISSUE THREAD

**Issue by jannuary** [hugolabe/Wike#48]
"Use Custom Font" option in settings uses a combo box, which is awkward and not searchable. GTK has a [standard font picker](https://docs.gtk.org/gtk4/iface.FontChooser.html) widget, which would be more fitting.

**Comment by hugolabe** [comment]
GTK FontButton is the most logical option and the first one I tried. The problem is that it gave me multiple errors and the Preferences window closed unexpectedly.

![wike-fontbutton](https://user-images.githubusercontent.com/18441950/132090921-bed5c303-e87d-4182-8942-24fcbf51e216.png)

I don't know why this happens and although I was trying to find more information I could not solve it, so I had to opt for an alternative approach.
