### ISSUE TITLE
Handle Wikipedia URL entry

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#50]
If you press <kbd>F2</kbd> or <kbd>Ctrl</kbd>+<kbd>K</kbd> it could handle URLs to Wikipedia articles.

Example if  you paste in:

    https://en.wikipedia.org/wiki/Linux

or

    https://en.m.wikipedia.org/wiki/Linux

Then it knows you want the Linux article.

**Comment by hugolabe** [comment]
This would make managing search entrie a lot more difficult and I don't see what use it could be. Wike is not a web browser.

**Comment by vanillajonathan** [comment]
No, Wike is not a web browser, but you might want to use Wike read an article you found using a web browser since Wike has features the Wikipedia website don't such as dark mode.

This would not need to be difficult and could be implemented simple:

```python
def do_activate(self):
    text = self.get_text()
    if text.startswith('https://en.wikipedia.org/wiki/'):
        text = text.lstrip('https://en.wikipedia.org/wiki/')
    elif text.startswith('https://en.m.wikipedia.org/wiki/'):
        text = text.lstrip('https://en.m.wikipedia.org/wiki/')
    # ...
```

**Comment by hugolabe** [comment]
You can paste the last part of the URL and Wike will find and open the article.

`https://en.wikipedia.org/wiki/Free_software` -> Free_software

**Comment by vanillajonathan** [comment]
Yes, I know that, but not everyone might know that, and it would be easier for users not to have to just be able to copy and paste the entire URL without have to take out the article part themselves.
It would be nice if the application was smart and intuitive and helped out users and worked with users instead of against users.

**Comment by hugolabe** [comment]
> Yes, I know that, but not everyone might know that, and it would be easier for users not to have to just be able to copy and paste the entire URL without have to take out the article part themselves.

I don't think the average user is going to copy URLs from a browser to the search box of another app. Not even the official Wikipedia app for Android supports that.

> This would not need to be difficult and could be implemented simple:

A introduction of new code is never trivial. The check you do only works for English Wikipedia, but there are almost 300 languages. And what happens if you paste a URL from a language other than the one that is active? Or do you paste an [alternate type url](https://en.wikipedia.org/wiki/Help:URL#URLs_of_Wikipedia_pages)? They would cause erratic behavior ... The application must handle all possibilities and check for errors that may occur.

Creating and maintaining an application takes time and effort, especially if you are not a programmer and do it in your free time. My approach for Wike is to keep it simple and focus on the essentials, without getting lost in adding a bunch of exotic features that I think hardly anyone is going to use.

**Comment by vanillajonathan** [comment]
Non-English language Wikipedia could be considered a corner case and ignored, so then it fallback to the existing current behavior, or solved using regular expressions.
