### ISSUE TITLE
Hidden bottom of some pictures

### ISSUE THREAD

**Issue by rene-coty** [hugolabe/Wike#70]
When clicking a picture to see it with the application's viewer, the bottom of the image is often hidden by the bottom-titlebar (with the author, license...). It apparently occurs when the picture is big. [picture1]
A solution is to click on the picture to make the bottom-titlebar disappear [picture2] and then to scroll down to see the bottom of the picture, but it's not very convenient, and there is a sort of blank / empty space on the left and right sides, which is not very esthetic.. [picture3]
![Picture1](https://user-images.githubusercontent.com/95506494/151665827-f03baecb-b38a-41e7-af96-f056de72c7bf.png)
![Picture2](https://user-images.githubusercontent.com/95506494/151665830-9e19f206-f5c8-400b-9ff2-407ff107ebeb.png)
![Picture3](https://user-images.githubusercontent.com/95506494/151665833-bcfdba57-f518-40e7-93fe-32815603b360.png)

**Comment by hugolabe** [comment]
The image viewer is part of the mobile view of Wikipedia, which Wike uses to display articles. The same thing happens if you view the page in any browser.

The bottom bar could be hidden using CSS, but that doesn't fix the issue...

![firefox-wikipedia](https://user-images.githubusercontent.com/18441950/152694946-87a17892-fa44-4000-8d88-b43d2a48180f.png)
