### ISSUE TITLE
Add flags to the language lists

### ISSUE THREAD

**Issue by vanillajonathan** [hugolabe/Wike#77]
Flags! 🇺🇦️

![image](https://user-images.githubusercontent.com/10222521/161308059-cd47bc98-f154-4294-9820-dc83bad4c275.png)

https://emojipedia.org/flags/

**Comment by hugolabe** [comment]
I've been playing around with the idea of adding flags, using this set: https://github.com/HatScripts/circle-flags.

![wike-flags](https://user-images.githubusercontent.com/18441950/161564494-dee29eba-91cf-441e-85db-a9b6490890cc.png)

I think it's a good option to help find a language at a glance, although it does present some difficulties.

There are no flags for all Wikipedia languages. One option would be to put only the most important languages and use a generic icon for the rest. They could be added later.

The flags do not have a direct correspondence with the languages, but with countries or regions and in many cases there are many countries that use the same language.

In some cases the choice seems obvious: UK for English or Spain for Spanish, since they are the original territories of that language. In others it is not so clear: which flag to choose for the Arab?

There are also countries that have several languages: traditional Chinese, simplified Chinese... Should we use the same flag?

**Comment by vanillajonathan** [comment]
There are also flag icons available in Unicode so you can use the font. But it may not be available on all fonts depending on what font is in use. Maybe it is possible to specify a font just for the flag but not for the text that overrides the system font to ensure a font that supports Unicode flag emojis are in use.

You do raise some interesting points, and the idea of using a generic flag for the rest sounds reasonable there are enough languages that has a suitable country icon for it to be a usability benefit that covers most languages for most people. If there are just a few languages without a suitable font then that might not be a big issue.

I do not like the circle icons, I would much prefer rectangular icons that are more reminiscent of actual flags.

In the Duolingo app they have country icons for their language course selection.
https://happilyevertravels.com/wp-content/uploads/2020/10/IMG_0603-576x1024.png.webp

**Comment by nekohayo** [comment]
Possibly a dangerous idea. Not only does this not necessarily have a match with geographic location, but flags are also politically charged, especially with independance-seeking regions (like Catalonia, Scotland, Québec vs Canada vs France, etc.). I think this is the reason why GNOME Settings and most installers don't sport any flags anywhere.

**Comment by hugolabe** [comment]
> Possibly a dangerous idea. Not only does this not necessarily have a match with geographic location, but flags are also politically charged, especially with independance-seeking regions (like Catalonia, Scotland, Québec vs Canada vs France, etc.). I think this is the reason why GNOME Settings and most installers don't sport any flags anywhere.

In general I agree with what you say, and I'm still not sure about implementing this feature. On the other hand, it makes it quite easy to find a language in the list.

One option could be to allow to disable the flags via an option in preferences, for those who don't want to use them.
