### ISSUE TITLE
feature request: keyboard shortcuts to change font size

### ISSUE THREAD

**Issue by janxkoci** [hugolabe/Wike#83]
I was surprised to find that the classic keyboard shortcuts `Ctrl++` and `Ctrl+-` did not increase and decrease the font size, as they do in web browsers.

Can we have such feature, pretty please? :blush:

**Comment by hugolabe** [comment]
The font size can be changed in the app preferences.

There are no keyboard shortcuts for this, but I don't think it's necessary. I think keyboard shortcuts should be reserved for commonly used functions.

In a browser it makes sense, because different websites have different designs and font sizes and in some cases it is useful to change it for a better display of the pages.

However, in Wike all articles have the same font size. Once you choose the most suitable size for you in the preferences, it should not be necessary to change it again.

**Comment by janxkoci** [comment]
You are right, it's nothing important. One possible use case would be if somebody borrows my computer to read something (possibly me showing them) and they want to quickly make the font bigger. But yes, it's very tiny corner case :)
