### ISSUE TITLE
Truncated sentences in Preferences

### ISSUE THREAD

**Issue by rene-coty** [hugolabe/Wike#97]
Some sentences in the Privacy section are truncated (at least when the UI is in French), and hovering them with the mouse doesn't make the text appear.
In this cas it prevents the user from knowing how to take full advantage of integrated research (with search prefixes)

![Capture d’écran du 2022-12-08 15-34-49](https://user-images.githubusercontent.com/95506494/206475114-809a1474-dfe1-47e8-9702-7009ec54af06.png)

**Comment by hugolabe** [comment]
I can make the window a bit bigger, but that doesn't fix the problem.

I think the solution must come from the translation itself. In translations it's important to try that the length of the sentences is not much greater than the original.

For example in this case it could be:

**Autoriser la recherche directement sur le bureau**
Attention: toutes les recherches seront envoyées à Wikipédia

**Les recherches sont faites dans le langage sélectionnée**
Pour d'autres langages utilisez un préfixe. Ex. -es pour l'espagnol

I don't know if these sentences are completely correct, since my knowledge of French is very limited. Translations can be edited in [POEditor](https://poeditor.com/join/project?hash=kNgJu4MAum).

**Comment by rene-coty** [comment]
Okay, I was unsure whether it would be a good idea to depart from these translations, since they seemed to respect the exact wording of the source strings (and anyway a French sentence will often be longer than it's English equivalent 😅️).. but if you suggest to do so I'll rewrite them to be shorter.

PS: thanks for the suggestions, they are quite good 😉️

**Comment by hugolabe** [comment]
I think that it is not important that the translations respect the original sentences exactly, since each language has its particularities. At least I don't worry much about that in Spanish translations. And, as you say, in some languages ​​the sentences tend to be quite a bit longer.

**Comment by hugolabe** [comment]
dbf7cb0f6f1b64f1fffbb20f01cffe875670a5af
